version: "3"

services:
  nginx:
    build: ./docker/nginx
    container_name: payjp-v2-form_nginx
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build: .
    container_name: payjp-v2-form_app
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    command: bundle exec ruby app.rb -o 0.0.0.0
